@@ -377,45 +377,3 @@ task :list do
   puts "Tasks: #{(Rake::Task.tasks - [Rake::Task[:list]]).join(', ')}"
   puts "(type rake -T for more detail)\n\n"
 end
-
- # add by chengzd ping sitemap
-
-desc 'Ping pingomatic'
-task :pingomatic do
-  begin
-    require 'xmlrpc/client'
-    puts '* Pinging ping-o-matic'
-    XMLRPC::Client.new('rpc.pingomatic.com', '/').call('weblogUpdates.extendedPing', 'Ewal.net' , 'http://zhongdechan.github.com', 'http://zhongdechan.github.com/atom.xml')
-  rescue LoadError
-    puts '! Could not ping ping-o-matic, because XMLRPC::Client could not be found.'
-  end
-end
-
-desc 'Notify Google of the new sitemap'
-task :sitemapgoogle do
-  begin
-    require 'net/http'
-    require 'uri'
-    puts '* Pinging Google about our sitemap'
-    Net::HTTP.get('www.google.com', '/webmasters/tools/ping?sitemap=' + URI.escape('http://zhongdechan.github.com/sitemap.xml'))
-  rescue LoadError
-    puts '! Could not ping Google about our sitemap, because Net::HTTP or URI could not be found.'
-  end
-end
-
-desc 'Notify Bing of the new sitemap'
-task :sitemapbing do
-  begin
-    require 'net/http'
-    require 'uri'
-    puts '* Pinging Bing about our sitemap'
-    Net::HTTP.get('www.bing.com', '/webmaster/ping.aspx?siteMap=' + URI.escape('http://zhongdechan.github.com/sitemap.xml'))
-  rescue LoadError
-    puts '! Could not ping Bing about our sitemap, because Net::HTTP or URI could not be found.'
-  end
-end
-
-desc "Notify various services about new content"
-task :notify => [:pingomatic, :sitemapgoogle, :sitemapbing] do
-end
-